### ISSUE TITLE
Battery percentage is on the right side

### ISSUE THREAD

**Issue by miguelcarax** [brendaw/add-username-toppanel#1]
Battery percentage is right after the name and not before it with the battery icon, is (wi-fi | sound | battery icon | username | battery percentage)

I have gnome 3.20 and Battery Status gnome-extension.

**Comment by brendaw** [comment]
Have you compiled by yourself or installed the extension by GNOME Shell Extensions, @miguelcarax? 

I've updated the extension here in github to support versions 3.20 and higher and not yet sent to the GNOME Shell Extensions.

**Comment by miguelcarax** [comment]
I cloned this on ~/.local/share/gnome-shell/extension and active it, thats all.

I'm running ArchLinux by the way.

**Comment by brendaw** [comment]
Sorry for the long waiting time :(

Which version of GNOME do you have right now? And have you tried to update your clone repo and tested again? Maybe the problem don't occur anymore.
