### ISSUE TITLE
Not working for certain users

### ISSUE THREAD

**Issue by kacastorp** [brendaw/add-username-toppanel#12]
On two different think pads user is shown as unknown but only for certain users.

**Comment by brendaw** [comment]
Hello, @kacastorp! Can you please send more info about this two think pads? Which OS and version do they run?  Is this new installations or old ones?

**Comment by kacastorp** [comment]
Yes sure. They are both X240s one with AMD and one with Intel. Both run up to date Fedora 37. There are six users and for no obvious reason one user is shown as unknown although in user management the users are there with  the names. I had creadted the users in comand line.

**Comment by kacastorp** [comment]
I found now, that the username only works for user with user ID 01

**Comment by brendaw** [comment]
I think that the problem might be on the user creation/configuration. 

Looking at our extension and how it grabs the user name, it uses a function to look up for the user name content located at `/etc/passwd` file. If in this file the field containing the user name is empty, then the function will return Unknown.

I'll put this info on README in the beginning of the next year (like... the next week 😅) to be more clear about the extension default behaviour.

So, I recommend you to look at your `/etc/passwd` and check if the users that are returning Unknown from this extension have the field for the real name of the user (like in the picture below):
![image](https://user-images.githubusercontent.com/3674847/210005925-bd7c1aab-5d05-4650-987f-869fda41e8a6.png)

Tell me if this helps you.

**Comment by kacastorp** [comment]
Thank you very much

William Brendaw ***@***.***> schrieb am Do., 29. Dez. 2022,
21:11:

**Comment by kacastorp** [comment]
You made my day,

yes that was the culprit. I don't know why the username was not inserted 
for these users when i created them by useradd and passwd. It would be 
good to put the info somwhere for those who run into the same problem.

Anyway thanks for this great extension.

Cheers

Wolfgang


Am 29.12.22 um 21:11 schrieb William Brendaw:

**Comment by brendaw** [comment]
Sometimes linux has its mysteries hehe.

I'm really happy for you and for the compliment :)

As I mentioned, I'll put this info as soon as possible and, when I do, I'll close this issue.
