### ISSUE TITLE
Add support for GNOME Shell 45

### ISSUE THREAD

**Issue by Josholith** [brendaw/add-username-toppanel#15]
Please update this extension with support for GNOME Shell 45.

Be aware there are significant changes in GNOME Shell 45 that require rewriting extensions using ESM style JavaScript.  This makes them incompatible with GNOME Shell 44 and below, which uses CommonJS style imports.  It's a breaking change, so you'll have to update the metadata.json to support only 45+.  But for versions 44-, the old version of the extension uploaded to the Extensions site can be left enabled to support the older Shell versions.  Users on 44 will not get the new version of this extension which would break them.  Once they update to 45, they will be able to get the new version (and they must get the new version to have it working.)

**Comment by Josholith** [comment]
If nobody picks this up, I'll probably take it on and make the PR for it.  I use and love this extension and would like to get it working on GNOME Shell 45.  I'm on Arch Linux and the main pacman made 45 available this week.   I'm a maintainer/author of another extension and recently did the 44->45 conversion, as a reference: https://github.com/Josholith/gnome-extension-lan-ip-address/pull/24

**Comment by brendaw** [comment]
Merged, and submitted to GNOME Extensions. Now is waiting review from them.

Thanks again for your contribution, @Josholith!
