### ISSUE TITLE
Add support for GNOME 42

### ISSUE THREAD

**Issue by Josholith** [brendaw/add-username-toppanel#7]

**Comment by cemozden** [comment]
I've created a PR for supporting the plugin in GNOME 42.

**Comment by brendaw** [comment]
Merged pull request #8 from @cemozden. Now I'll put on GNOME Shell Extensions sooner. 

Thanks for pointing this issue, @Josholith, and @cemozden for the pull request!

**Comment by Josholith** [comment]
@brendaw ... Code looks good here for GNOME 42, but I'm still seeing only up to GNOME 41 on the GNOME Extensions site:
https://extensions.gnome.org/extension/1108/add-username-to-top-panel/

Did you upload the new Zip file to GNOME Extensions site?  Since your latest updates only needed to change the metadata & Readme changes it should have auto-approved and published.  Thanks for looking!

**Comment by brendaw** [comment]
Hi, @Josholith!

First of all, thanks for pointing that out for me!

I've thought that it was already in the next version, but for some reason it was not activated on Gnome Extensions. I have now activated the new version with support for Gnome 42. 

Let me know if it will rise any problem. Thanks again for your heads up!
