### ISSUE TITLE
Please add support for Gnome 43

### ISSUE THREAD

**Issue by Sharath44665** [brendaw/add-username-toppanel#9]
Hi admin,

Please add support for Gnome 43, thanks

**Comment by Sharath44665** [comment]
GNOME Shell 43 removed aggregateMenu

**Comment by GithubUser699** [comment]
> GNOME Shell 43 removed aggregateMenu

Are you saying that it's impossible to add this feature in GNOME 43?

I really liked this feature and would like to see it back. I'd try to implement it myself, even though I don't know much about programming extensions, but if it's not going to be possible to add it somehow anymore that would be good (and sad) to know.

**Comment by brendaw** [comment]
Hello, there.

I'm sad that the extension lost support in GNOME 43. This week I will investigate this issue and try to fix it as soon as possible.

I'm really sorry that this happened.

Stay tuned because this adjustment should soon go up.

**Comment by Sharath44665** [comment]
> > GNOME Shell 43 removed aggregateMenu
> 
> Are you saying that it's impossible to add this feature in GNOME 43?
> 
> I really liked this feature and would like to see it back. I'd try to implement it myself, even though I don't know much about programming extensions, but if it's not going to be possible to add it somehow anymore that would be good (and sad) to know.

#### I forked this repo and worked on it to fix the issue by myself, but I am unable to fix it from my end. So I checked the gnome documentation, and yeah, I raised the issue here.

It is possible to add this feature, but somehow I don't know how to do it.

**Comment by Sharath44665** [comment]
I truly apologise for accidentally closing the issue

**Comment by Sharath44665** [comment]
> Hello, there.
> 
> I'm sad that the extension lost support in GNOME 43. This week I will investigate this issue and try to fix it as soon as possible.
> 
> I'm really sorry that this happened.
> 
> Stay tuned because this adjustment should soon go up.

### Thank you very much for your comment.

_There is no need to apologize_

### eager to see this extension again
